In [1]:
'''
Overview
this notebook parses all fighters' details and tale of the tape

scrape ufc fighters' details
includes first, last, nickname, url
from url scrape scrape fighter's tale of the tape, 
includes fighter, height, weight, reach, stance, dob
'''

"\nOverview\nthis notebook parses all fighters' details and tale of the tape\n\nscrape ufc fighters' details\nincludes first, last, nickname, url\nfrom url scrape scrape fighter's tale of the tape, \nincludes fighter, height, weight, reach, stance, dob\n"

In [2]:
# imports
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm_notebook

# import library
import scrape_ufc_stats_library as LIB
import importlib
importlib.reload(LIB)

# import configs
import yaml
config = yaml.safe_load(open('scrape_ufc_stats_config.yaml'))

# Parse Fighter Details
Includes:
<br>
First
<br>
Last
<br>
Nickname
<br>
URL

In [3]:
# generate list of urls for fighter details
list_of_alphabetical_urls = LIB.generate_alphabetical_urls()

In [4]:
# create empty dataframe to store all fighter details
all_fighter_details_df = pd.DataFrame()

# loop through list of alphabetical urls
for url in tqdm_notebook(list_of_alphabetical_urls):
    # get soup
    soup = LIB.get_soup(url)
    # parse fighter details
    fighter_details_df = LIB.parse_fighter_details(soup, config['fighter_details_column_names'])
    # concat fighter_details_df to all_fighter_details_df
    all_fighter_details_df = pd.concat([all_fighter_details_df, fighter_details_df])

# show all fighter details
display(all_fighter_details_df)

# write to file
all_fighter_details_df.to_csv(config['fighter_details_file_name'], index=False)

  0%|          | 0/26 [00:00<?, ?it/s]

,FIRST,LAST,NICKNAME,URL
0,Tom,Aaron,,http://ufcstats.com/fighter-details/93fe7332d1...
1,Danny,Abbadi,The Assassin,http://ufcstats.com/fighter-details/15df64c02b...
2,Nariman,Abbasov,Bayraktar,http://ufcstats.com/fighter-details/59a9d6dac6...
3,Darion,Abbey,,http://ufcstats.com/fighter-details/4961467134...
4,David,Abbott,Tank,http://ufcstats.com/fighter-details/b361180739...
...,...,...,...,...
37,Alex,Zuniga,,http://ufcstats.com/fighter-details/02d808afb9...
38,George,Zuniga,,http://ufcstats.com/fighter-details/1291dd6b8a...
39,Allan,Zuniga,Tigre,http://ufcstats.com/fighter-details/523af801b3...
40,Brahyam,Zurcher,El Jarretas,http://ufcstats.com/fighter-details/392878af46...
41,Virgil,Zwicker,RezDog,http://ufcstats.com/fighter-details/0c277f3ff6...

# Parse Fighter Tale of the Tape

Includes:
<br>
Fighter
<br>
Height
<br>
Weight
<br>
Reach
<br>
Stance
<br>
DOB
<br>
URL

In [5]:
# define list of urls of fighters to parse
list_of_fighter_urls = list(all_fighter_details_df['URL'])

In [6]:
# create empty df to store fighters' tale of the tape
all_fighter_tott_df = pd.DataFrame(columns=config['fighter_tott_column_names'])

# loop through list_of_fighter_urls
for url in tqdm_notebook(list_of_fighter_urls):
    # get soup
    soup = LIB.get_soup(url)
    # parse fighter tale of the tape
    fighter_tott = LIB.parse_fighter_tott(soup)
    # organise fighter tale of the tape
    fighter_tott_df = LIB.organise_fighter_tott(fighter_tott, config['fighter_tott_column_names'], url)
    # concat fighter
    all_fighter_tott_df = pd.concat([all_fighter_tott_df, fighter_tott_df])

# show all fighters' tale of the tape
display(all_fighter_tott_df)

# write to file
all_fighter_tott_df.to_csv(config['fighter_tott_file_name'], index=False)

  0%|          | 0/4489 [00:00<?, ?it/s]

,FIGHTER,HEIGHT,WEIGHT,REACH,STANCE,DOB,URL
0,Tom Aaron,--,155 lbs.,--,,"Jul 13, 1978",http://ufcstats.com/fighter-details/93fe7332d1...
0,Danny Abbadi,"5' 11""",155 lbs.,--,Orthodox,"Jul 03, 1983",http://ufcstats.com/fighter-details/15df64c02b...
0,Nariman Abbasov,"5' 8""",155 lbs.,"66""",Orthodox,"Feb 01, 1994",http://ufcstats.com/fighter-details/59a9d6dac6...
0,Darion Abbey,"6' 2""",265 lbs.,"80""",Orthodox,"Feb 25, 1993",http://ufcstats.com/fighter-details/4961467134...
0,David Abbott,"6' 0""",265 lbs.,--,Switch,"Apr 26, 1965",http://ufcstats.com/fighter-details/b361180739...
...,...,...,...,...,...,...,...
0,Alex Zuniga,--,145 lbs.,--,,--,http://ufcstats.com/fighter-details/02d808afb9...
0,George Zuniga,"5' 9""",185 lbs.,--,,--,http://ufcstats.com/fighter-details/1291dd6b8a...
0,Allan Zuniga,"5' 7""",155 lbs.,"70""",Orthodox,"Apr 04, 1992",http://ufcstats.com/fighter-details/523af801b3...
0,Brahyam Zurcher,"5' 10""",145 lbs.,"70""",Orthodox,"Mar 10, 1996",http://ufcstats.com/fighter-details/392878af46...
0,Virgil Zwicker,"6' 2""",205 lbs.,"74""",,"Jun 26, 1982",http://ufcstats.com/fighter-details/0c277f3ff6...